name: Check Creation of Wheel Package
on: [pull_request]

jobs:
  python-wheel-check:
    name: Unit-Test Check for ${{ matrix.path }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
      - name: Create Wheel Package
        run: (cd opload; python setup.py bdist_wheel)
      - name: Install Wheel Package
        run: python -m pip install opload/dist/opload*.whl
      - name: Execute Simple Command to Verify Installation
        run: |
          opload version